# for development (auto-reload via runserver)
version: "3.9"

services:
  web:
    image: maintenatrack:local
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - .:/app          # 👈 Mount source code into container
   

