# Generated by Django 5.2.6 on 2025-09-23 22:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="step",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="zone",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Default/primary zone for this equipment (1–22).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="description",
            field=models.TextField(
                help_text="Problem statement and high-level approach."
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked asset, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="maintenance.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="zone",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Physical Zone/Cell where the issue occurred (1–22).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(22),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                fields=("log", "order"), name="unique_step_order_per_log"
            ),
        ),
    ]
