# Generated by Django 5.2.6 on 2025-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_step_unique_together_alter_equipment_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Unique asset identifier (optional on quick add).', max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('name', 'zone'), name='unique_equipment_name_per_zone'),
        ),
    ]
