# Generated by Django 5.2.6 on 2025-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_equipment_asset_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='zone',
            field=models.CharField(db_index=True, help_text="Zone identifier for this equipment (e.g., '1', 'A1', 'Zone-5').", max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='alarm_code',
            field=models.CharField(db_index=True, help_text="Alarm code - accepts numbers, letters, or mixed (e.g., '123', 'ALM-456', 'A1B2').", max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='zone',
            field=models.CharField(db_index=True, help_text="Zone identifier where the issue occurred (e.g., '1', 'A1', 'Zone-5').", max_length=10),
        ),
    ]
